version: "3.8"

services:
  digit-caster-be:
    container_name: digit-caster-be
    image: digit-caster-be:1.0
    build: ./
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:9000
    networks:
      digit-caster-net:
        ipv4_address: 172.28.1.1

networks:
  digit-caster-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16